### ISSUE TITLE
1806-18 RITTENHOUSE SQ base address with no assessment return

### ISSUE THREAD

**Issue by tswanson** [CityOfPhiladelphia/atlas#30]
When an address is entered that is a valid Base address but there are no OPA records associated with it directly, need to let the users know to go to related records.

@Alexander-M-Waldman is there anything in AIS that can be done to flag this with users?

**Comment by Alexander-M-Waldman** [comment]
@tswanson in AIS the `?include_units` flag can be appended to a base address query to return any child_units along with the base address in the response.  Will this address the need here?
